create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table clients (id varchar(255) not null, access_token_ttl bigint, client_id varchar(255) not null, issued_at timestamp(6), name varchar(255), refresh_token_ttl bigint, primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists clients drop constraint if exists UK2og8x0i6lngghy4cqupje9dki;
alter table if exists clients add constraint UK2og8x0i6lngghy4cqupje9dki unique (client_id);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table clients (id varchar(255) not null, access_token_ttl bigint, client_id varchar(255) not null, issued_at timestamp(6), name varchar(255), refresh_token_ttl bigint, primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists clients drop constraint if exists UK2og8x0i6lngghy4cqupje9dki;
alter table if exists clients add constraint UK2og8x0i6lngghy4cqupje9dki unique (client_id);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table clients (id varchar(255) not null, access_token_ttl bigint, client_id varchar(255) not null, issued_at timestamp(6), name varchar(255), refresh_token_ttl bigint, primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists clients drop constraint if exists UK2og8x0i6lngghy4cqupje9dki;
alter table if exists clients add constraint UK2og8x0i6lngghy4cqupje9dki unique (client_id);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
create table api_scopes (id varchar(255) not null, name varchar(255), primary key (id));
create table client_api_scope (client_id varchar(255) not null, api_scope_id varchar(255) not null, primary key (client_id, api_scope_id));
create table client_audience_uris (client_id varchar(255) not null, audience_uri varchar(255));
create table client_grant_types (client_id varchar(255) not null, grant_type varchar(255));
create table client_secrets (id varchar(255) not null, client_id varchar(255), expires_at timestamp(6), issued_at timestamp(6), secret varchar(255), primary key (id));
create table clients (id varchar(255) not null, access_token_ttl bigint, client_id varchar(255) not null, issued_at timestamp(6), name varchar(255), refresh_token_ttl bigint, primary key (id));
create table refresh_tokens (id varchar(255) not null, client_id varchar(255), expired_at timestamp(6), user_id varchar(255), value varchar(255), primary key (id));
create table users (id varchar(255) not null, email varchar(255), password varchar(255), phone_number varchar(255), username varchar(255) not null, primary key (id));
alter table if exists api_scopes drop constraint if exists UK3ouyu3mqt07um9jin2tpw3r9j;
alter table if exists api_scopes add constraint UK3ouyu3mqt07um9jin2tpw3r9j unique (name);
alter table if exists clients drop constraint if exists UK2og8x0i6lngghy4cqupje9dki;
alter table if exists clients add constraint UK2og8x0i6lngghy4cqupje9dki unique (client_id);
alter table if exists refresh_tokens drop constraint if exists UK49ntxwlntp8kp4u0gge8g8oot;
alter table if exists refresh_tokens add constraint UK49ntxwlntp8kp4u0gge8g8oot unique (value);
alter table if exists users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists client_api_scope add constraint FK6lp2wu8c6g93aotrh95qc0qcq foreign key (api_scope_id) references api_scopes;
alter table if exists client_api_scope add constraint FK91493nmo34evgtlx61yc39un1 foreign key (client_id) references clients;
alter table if exists client_audience_uris add constraint FKls50o7nxloevaugpg08q4rsvp foreign key (client_id) references clients;
alter table if exists client_grant_types add constraint FKqr55dq5fnb0fq2l3gu6bafc94 foreign key (client_id) references clients;
alter table if exists client_secrets add constraint FKjoq9qaxbktk6to8hfmhxcapwv foreign key (client_id) references clients;
